@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center

participant "v : Car" as V
participant "lane : OutdoorLane" as L
participant "state : SaltedState" as ST

V -> L : interactWithLane(v)
activate L
    L -> ST : handleTraffic(lane, v)
    activate ST
        note right: A só megakadályozza a jegesedést
        ST -->> L : state (this)
    deactivate ST
    
    L -->> V : 
deactivate L
@enduml