@startuml
skinparam style strictuml

actor "Buszvezető" as B
participant "bus : Bus" as BUS
participant "l : Lane" as L

B -> BUS : nextTurn()
activate BUS
    BUS -> L : acceptVehicle(BUS)
    activate L
    L --> BUS : true
    deactivate L
    
    BUS -> BUS : interactWithRoad()
    
    note over BUS: Ha elérte az egyik végállomást (stop1/stop2)
    BUS -> BUS : updateIncome(turnReward)
    note right: Forduló elszámolása
    
BUS --> B
deactivate BUS
@enduml