@startuml
' UC10: Hókotró fej csere
skinparam style strictuml
skinparam sequenceMessageAlign center

actor "tesztelő" as T
participant "snowplow : SnowPlow" as P
participant "cleaner : Cleaner" as C
participant "iceBreaker : IceBreaker" as I

T -> P : buyAttachment(iceBreaker)
activate P
    P -> I : getPrice()
    activate I
    I -->> P : 3
    deactivate I
    P -> C : getScore()
    activate C
    C -->> P : 100
    deactivate C
    note right: 3 <= 100 → vásárlás lehetséges\nownedTools.add(iceBreaker)
    P -> C : getScore()
    activate C
    C -->> P : 100
    deactivate C
    P -> I : getPrice()
    activate I
    I -->> P : 3
    deactivate I
    P -> C : setScore(97)
    activate C
    deactivate C
    P -->> T : true
deactivate P

T -> P : changeAttachment(iceBreaker)
activate P
    note right: ownedTools.contains(iceBreaker) → igaz\ncurrentTool = iceBreaker
    P -->> T : true
deactivate P
@enduml
