@startuml class-diagram
abstract Vehicle {
  # currentLane: Lane
  # timeOutStart: int
  + nextTurn()
  + interactWithLane(l: Lane)
  + setImmobilized()
}
class Bus {
  - balance: int
  + interactWithLane(l: Lane)
  + addIncome(amount: int)
  + getScore(): int
}
class SnowPlow {
  + changeAttachment(a: Attachment): bool
  + buyAttachment(new: Attachment): bool
  + refillAttachment()
  + interactWithLane(l: Lane)
  + crash(timestamp: int)
}
class Car {
  + interactWithLane(l: Lane)
}
abstract Attachment {
  # price: int
  + cleanLane(l: Lane, timestamp: int): bool
  + getPrice(): int
  + refill(budget: int): int
}
class Dragon {
  - priceOfFuel: int
  + cleanLane(l: Lane, timestamp: int): bool
  + refill(budget: int): int
}
class Sweeper
class VomitingHead
class IceBreaker
class SaltVomitter {
  - priceOfFuel: int
  + cleanLane(l: Lane, timestamp: int): bool
  + refill(budget: int): int
}
interface IAttachment {
  + cleanLane(l: Lane, timestamp: int): bool
  + getPrice(): int
  + refill(budget: int): int
}
class Road {
  + snowFall()
}
class Lane {
  - snowLevel: int
  - icingCounter: int
  - isAvailable: bool
  - isIcy: bool
  + acceptVehicle(v: Vehicle)
  + snowFall()
}
class Junction
class Cleaner {
  - balance: int
  + addIncome(amount: int)
  + getScore(): int
}
abstract class Commuter {
  + turnAround()
}
interface IControllable {
  + gotoLane(l: Lane, timestamp: int): bool
  + crash(timestamp: int)
  + interactWithLane(l: Lane)
}
interface ISnowPlow {
  + buyAttachment(a: Attachment): bool
  + changeAttachment(a: Attachment): bool
  + refillAttachment()
}
interface IRouteHandler {
  + turnAround()
}
interface IScoreOwner {
  + getScore(): int
}

Road "4" *-- "1" Lane
Dragon --|> Attachment
Sweeper --|> Attachment
VomitingHead --|> Attachment
IceBreaker --|> Attachment
SaltVomitter --|> Attachment
Attachment ..|> IAttachment
Road "2" o--o Junction
Vehicle "1" o--o Lane
Commuter "1" o-- "1" Road : destination1
Commuter "1" o-- "1" Road : destination2
Vehicle ..|> IControllable
SnowPlow --|> Vehicle
SnowPlow ..|> ISnowPlow
Commuter --|> Vehicle
Commuter ..|> IRouteHandler
Bus --|> Commuter
Bus ..|> IScoreOwner
Car --|> Commuter
Cleaner ..|> IScoreOwner
Cleaner "1" *-- "1..*" SnowPlow : controls
SnowPlow "1" o-- "1..*" Attachment : owned_tools
SnowPlow "1" o-- "1" Attachment : active_tool
SnowPlow "1" --> "1" Cleaner : owner
@enduml
