@startuml
' SD-UI-04: Sáv állapotváltozása – LaneView frissítése
skinparam style strictuml
skinparam sequenceMessageAlign center

participant "model" as Model
participant "l : Lane" as L
participant "lv : LaneView" as LV
participant "jv : JunctionView" as JV
participant "vv : VehicleView" as VV
participant "cv : CleanerView" as CV
participant "gp : GamePanel" as GP


Model -> L : [állapotváltozást okozó esemény]
activate L
    L -> L : notifyObservers()
    L -> LV : update()
    activate LV
        LV -> L : [aktuális állapot lekérdezése]
        note right: száraz, havas, jeges stb.
        LV -> LV : szín beállítása
        LV -> GP : repaint()
    deactivate LV
deactivate L

GP -> GP : paintComponent(g)
activate GP
    GP -> JV : draw(g)
    activate JV
        JV -> JV : g.fillRect(x, y, width, height)
    deactivate JV
    GP -> LV : draw(g)
    activate LV
        LV -> LV : g.fillRect(x, y, width, height)
    deactivate LV
    GP -> VV : draw(g)
    activate VV
        VV -> VV : g.fillRect(x, y, width, height)
    deactivate VV
    GP -> CV : draw(g)
    activate CV
        CV -> CV : g.fillRect(x, y, width, height)
    deactivate CV
deactivate GP
@enduml
