@startuml
actor "Autó / Busz Vezető" as A
participant "v: Vehicle" as V
participant "target: Lane" as L

A -> V : nextTurn()
activate V
    V -> V : checkMobility()
    
    alt isImmobilized == false
        V -> L : acceptVehicle(v)
        activate L
            alt snowLevel > 5
                L -> V : setImmobilized()
                L --> V : false
            else isIcy == true
                L -> V : setImmobilized()
                L --> V : true
            else isAvailable == true
                L --> V : true
            end
        deactivate L
        
        V -> V : interactWithRoad()
    end
deactivate V
@enduml