@startuml
actor "Takarító" as T
participant "p: SnowPlow" as P
participant "a: Attachment" as A
participant "l: Lane" as L

T -> P : interactWithRoad()
activate P
    P -> A : cleanLane()
    activate A
        alt Söprő / Hányó fej
            A -> L : snowLevel = 0
        else Jégtörő fej
            A -> L : isIcy = false
        else Sárkány / Sószóró
            A -> L : snowLevel = 0
            A -> L : isIcy = false
        end
        A --> P : success
    deactivate A
    
    P -> P : updateIncome()
deactivate P
@enduml