@startuml
actor "Takarító" as T
participant "p: SnowPlow" as P
participant "a: Attachment" as A

T -> P : buyAttachment()
activate P
    alt income >= attachmentPrice
        P -> P : income -= attachmentPrice
      
        P --> T : true
    else nincs elég pénz
        P --> T : false
    end
deactivate P

T -> P : changeAttachment(new)
activate P
    create "new: Attachment" as NA
    P -> NA : <<create>>
deactivate P

T -> P : refillAttachment()
activate P
    P -> A : refill()
deactivate P
@enduml