@startuml
actor "Takarító" as T
participant "p: SnowPlow" as P
participant "a: Attachment" as A

T -> P : changeAttachment(new)
activate P
    create "new: Attachment" as NA
    P -> NA : <<create>>
deactivate P

T -> P : refillAttachment()
activate P
    P -> A : refill()
deactivate P

T -> P : buyAttachment()
activate P
    note right: Az income attribútum csökken
deactivate P
@enduml