@startuml
actor "Rendszer" as S
participant "r: Road" as R
participant "l: Lane" as L
participant "v1: Vehicle" as V1
participant "v2: Vehicle" as V2

S -> R : snowFall()
activate R
    R -> L : snowFall()
    activate L
        note right: snowLevel++
    deactivate L
deactivate R

V1 -> L : acceptVehicle(v1)
activate L
    alt isIcy == true ÉS l.currentVehicle != null
        L -> V1 : setImmobilized()
        L -> V2 : setImmobilized()
        L -> L : isAvailable = false
        note right: A sáv lezárul (isAvailable = false)
    end
    L --> V1 : returnCode
deactivate L
@endumls