@startuml
actor "Idő / Rendszer" as E
participant "r: Road" as R
participant "l: Lane" as L
participant "v1: Vehicle" as V1
participant "v2: Vehicle" as V2

E -> R : snowFall()
activate R
    R -> L : snowFall()
    activate L
        note right: l.snowLevel növekszik
    deactivate L
deactivate R

V1 -> L : acceptVehicle(v1)
activate L
    alt isIcy == true ÉS l.currentVehicle != null
        L -> V1 : setImmobilized()
        L -> V2 : setImmobilized()
        L -> L : isAvailable = false
    end
    L --> V1 : return
deactivate L
@enduml