@startuml
actor "Autó / Busz Vezető" as T
actor "Idő / Rendszer" as E
participant "v_new: Vehicle" as V
participant "l: OutdoorLane" as L
participant "s: IcyState" as S
participant "v_old: Vehicle" as VO

' --- hóesős szakasz ---
group Havazás (külön folyamat)
    E -> L : snowFall()
    activate L
        L -> S : handleSnow(l, amount)
    deactivate L
end

' --- mozgós+ütközős szakasz ---
group Következő kör / Mozgás
    T -> V : nextTurn()
    activate V
        V -> L : acceptVehicle(v_new)
        activate L
            L -> S : handleTraffic(l, v_new)
            activate S
                
                alt IcyState: Csúszás veszélye
                    
                    loop minden v_old a sávban (l.getVehicles())
                        
                        opt véletlenszerű ütközés bekövetkezik
                            S -> V : crash(timestamp)
                            S -> VO : crash(timestamp)
                            S -> L : isAvailable = false
                            note right: Ütközésnél a sáv járhatatlanná válik
                            
                        
                            return crash_occurred
                        end
                        
                    end
                end
                
                S --> L : success
            deactivate S
            L --> V : ret
        deactivate L
    deactivate V
end
@enduml